
DELETE FROM warehouse_physical_info;
ALTER TABLE warehouse_physical_info AUTO_INCREMENT=1;
INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('901','Alog_cd','心怡成都仓','心怡','510000','四川','510100','成都','510112','龙泉驿区','汽车城大道17号普洛斯园区B1-1  ','张志荣','13438234152','2017-07-31 15:10:04','2017-07-28 14:45:53','admin','admin');
INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('902','STORE_CQYT','心怡重庆仓','心怡','500000','重庆','500100','重庆','202020','两江新区','礼环北路10号','','','2017-07-28 16:57:02','2017-07-28 16:57:02','admin','admin');

DELETE FROM warehouse_logic_info;
ALTER TABLE warehouse_logic_info AUTO_INCREMENT=1;
insert into warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) values('1','901200411','成都仓四川子公司常温正常仓','10000','20041','成都子公司','1','1','2017-08-03 14:11:26','2017-08-03 14:11:33','admin','admin');
insert into warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) values('2','902200421','重庆仓重庆子公司常温正常仓','10005','20042','重庆子公司','1','1','2017-08-03 14:11:29','2017-08-03 14:11:35','admin','admin');



INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('903','Alog_cs','心怡长沙仓','心怡','430000','湖南','430100','长沙','430181','浏阳市','永安镇人人家维龙-1','郭君','13407338311',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('904','STORE_WH','心怡武汉仓','心怡','420000','湖北','420100','武汉','420115','江夏区','庙山开发区特2号','周云龙','18810519904',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('905','STORE_SZ','际链深圳仓','际链','440000','广东','441900','东莞','441900117','凤岗镇','怡红路国新物流园','王文华','13907091279',NOW(),NOW(),'admin','admin');


INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES('3','903200451','长沙仓湖南子公司常温正常仓','10004','20045','湖南子公司','1','1',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES('4','904200501','武汉仓湖北子公司常温正常仓','10014','20050','湖北子公司','1','1',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES('5','905200461','深圳仓广东子公司常温正常仓','100009','20046','广东子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('908','STORE_HZYT','际链杭州仓','际链','330000','浙江','330100','杭州','330104','江干区','下沙文海北路370号','殷泷炜','13801918353',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '908'),'908200551','杭州仓浙江子公司常温正常仓','10020','20055','浙江子公司','1','1',NOW(),NOW(),'admin','admin');


INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('909','STORE_SJZYT','际链石家庄仓','际链','130000','河北','130100','石家庄','130123','正定县','石家庄市正定新区107国道边，正定国际物流园1号库','郝宗辉','18032137766',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '909'),'909200441','石家庄仓河北子公司常温正常仓','10008','20044','河北子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('911','STORE_ZZYT','心怡郑州仓','心怡','410000','河南','410100','郑州','410105','金水区','郑州市科学大道与绕城高速西2公里阳光物流园','钱丽霞','18069829860',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '911'),'911200561','郑州仓河南子公司常温正常仓','10012','20056','河南子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('907','STORE_BJYT','际链北京仓','际链','110000','北京','110100','北京','110105','朝阳区','北京市朝阳区黑庄户万通路8号','赵宁','15810426506',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '907'),'907200431','北京仓北京子公司常温正常仓','10006','20043','北京子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('910','STORE_GZYT','际链广州仓','际链','440000','广东','441900','东莞','441900003','东城区','环城东路桑园鼎好广场伟盛1号楼','杨文隆‭‬','18502007508',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '910'),'910200461','广州仓广东子公司常温正常仓','10022','20046','广州(广东子公司直营)','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('912','STORE_BJYT','心怡西安仓','心怡','610000','陕西','610400','咸阳','610404','渭城区','渭城区X324(韩双路北200米)','张玉坤','18660429060',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '912'),'912200521','西安仓陕西子公司常温正常仓','10010','20052','陕西子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('1000','STORE_XGYT','心怡香港仓','心怡','810000','香港','810100','香港','810007','九龙城区','西九龙海庭道','陈增荣','11686132158',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '1000'),'1000209981','香港仓香港子公司常温正常仓','100043','20998','测试香港分公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('1001','STORE_TWYT','际链台湾仓','际链','710000','台湾','710000','台湾','711900','嘉义县','梅山太和村社后坪','张鑫','18648546145',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '1001'),'1001209991','台湾仓台湾子公司常温正常仓','100066','20999','测试台湾分公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('913','STORE_XGNC','际链南昌仓','际链','360000','江西','360100','南昌','360121','小蓝开发区','南昌市小蓝开发区金沙大道1388号内的2#库房','刘金仁','13666026106',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '913'),'913200611','南昌仓江西子公司常温正常仓','100045','20061','江西子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('914','STORE_TWKM','际链昆明仓','际链','530000','云南','530100','昆明','530122','晋宁区','昆阳街道昆孟线中谊村站西南500米','刘典坤','18696698818',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '914'),'914200631','昆明仓云南子公司常温正常仓','100052','20063','云南子公司','1','1',NOW(),NOW(),'admin','admin');

INSERT INTO warehouse_physical_info (warehouse_code, third_warehouse_code, warehouse_name, warehouse_service, province_code, province, city_code, city, county_code, county, address, contact_person, contact_mode, create_time, modify_time, create_user, modify_user) VALUES('915','STORE_TWYY','际链益阳仓','际链','430000','湖南','430900','益阳','430903','赫山区','湖南省益阳市赫山区玉兰路268号','葛辰','13801633964',NOW(),NOW(),'admin','admin');
INSERT INTO warehouse_logic_info (physical_warehouse_id, warehouse_code, warehouse_name, branch_company_id, branch_company_code, branch_company_name, logic_type, storage_type, create_time, modify_time, create_user, modify_user) VALUES((SELECT id FROM warehouse_physical_info wi WHERE wi.warehouse_code = '915'),'915200451','益阳仓湖南子公司常温正常仓','10004','20045','湖南子公司','1','1',NOW(),NOW(),'admin','admin');
