-- 导出  表 act_re_deployment 结构  
DROP TABLE IF EXISTS `act_re_deployment`;  
CREATE TABLE IF NOT EXISTS `act_re_deployment` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `CATEGORY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `DEPLOY_TIME_` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_ge_bytearray 结构  
DROP TABLE IF EXISTS `act_ge_bytearray`;  
CREATE TABLE IF NOT EXISTS `act_ge_bytearray` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `DEPLOYMENT_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `BYTES_` LONGBLOB,  
  `GENERATED_` TINYINT(4) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_FK_BYTEARR_DEPL` (`DEPLOYMENT_ID_`),  
  CONSTRAINT `ACT_FK_BYTEARR_DEPL` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `act_re_deployment` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
    
-- 导出  表 act_ge_property 结构  
DROP TABLE IF EXISTS `act_ge_property`;  
CREATE TABLE IF NOT EXISTS `act_ge_property` (  
  `NAME_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `VALUE_` VARCHAR(300) COLLATE utf8_bin DEFAULT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  PRIMARY KEY  (`NAME_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
insert into `act_ge_property` (`NAME_`, `VALUE_`, `REV_`) values('next.dbid','1','1');
insert into `act_ge_property` (`NAME_`, `VALUE_`, `REV_`) values('schema.history','create(5.22.0.0)','1');
insert into `act_ge_property` (`NAME_`, `VALUE_`, `REV_`) values('schema.version','5.22.0.0','1');

-- 导出  表 act_hi_actinst 结构  
DROP TABLE IF EXISTS `act_hi_actinst`;  
CREATE TABLE IF NOT EXISTS `act_hi_actinst` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `ACT_ID_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `CALL_PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `ACT_NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `ACT_TYPE_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `ASSIGNEE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `START_TIME_` DATETIME NOT NULL,  
  `END_TIME_` DATETIME DEFAULT NULL,  
  `DURATION_` BIGINT(20) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_HI_ACT_INST_START` (`START_TIME_`),  
  KEY `ACT_IDX_HI_ACT_INST_END` (`END_TIME_`),  
  KEY `ACT_IDX_HI_ACT_INST_PROCINST` (`PROC_INST_ID_`,`ACT_ID_`),  
  KEY `ACT_IDX_HI_ACT_INST_EXEC` (`EXECUTION_ID_`,`ACT_ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_hi_attachment 结构  
DROP TABLE IF EXISTS `act_hi_attachment`;  
CREATE TABLE IF NOT EXISTS `act_hi_attachment` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `USER_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `DESCRIPTION_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `URL_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `CONTENT_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_hi_comment 结构  
DROP TABLE IF EXISTS `act_hi_comment`;  
CREATE TABLE IF NOT EXISTS `act_hi_comment` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TIME_` DATETIME NOT NULL,  
  `USER_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `ACTION_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `MESSAGE_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `FULL_MSG_` LONGBLOB,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
 
-- 导出  表 act_hi_detail 结构  
DROP TABLE IF EXISTS `act_hi_detail`;  
CREATE TABLE IF NOT EXISTS `act_hi_detail` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `ACT_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `VAR_TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `TIME_` DATETIME NOT NULL,  
  `BYTEARRAY_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DOUBLE_` DOUBLE DEFAULT NULL,  
  `LONG_` BIGINT(20) DEFAULT NULL,  
  `TEXT_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `TEXT2_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_HI_DETAIL_PROC_INST` (`PROC_INST_ID_`),  
  KEY `ACT_IDX_HI_DETAIL_ACT_INST` (`ACT_INST_ID_`),  
  KEY `ACT_IDX_HI_DETAIL_TIME` (`TIME_`),  
  KEY `ACT_IDX_HI_DETAIL_NAME` (`NAME_`),  
  KEY `ACT_IDX_HI_DETAIL_TASK_ID` (`TASK_ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_hi_identitylink 结构  
DROP TABLE IF EXISTS `act_hi_identitylink`;  
CREATE TABLE IF NOT EXISTS `act_hi_identitylink` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `GROUP_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `USER_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_HI_IDENT_LNK_USER` (`USER_ID_`),  
  KEY `ACT_IDX_HI_IDENT_LNK_TASK` (`TASK_ID_`),  
  KEY `ACT_IDX_HI_IDENT_LNK_PROCINST` (`PROC_INST_ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_hi_procinst 结构  
DROP TABLE IF EXISTS `act_hi_procinst`;  
CREATE TABLE IF NOT EXISTS `act_hi_procinst` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `BUSINESS_KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `START_TIME_` DATETIME NOT NULL,  
  `END_TIME_` DATETIME DEFAULT NULL,  
  `DURATION_` BIGINT(20) DEFAULT NULL,  
  `START_USER_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `START_ACT_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `END_ACT_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `SUPER_PROCESS_INSTANCE_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DELETE_REASON_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  UNIQUE KEY `PROC_INST_ID_` (`PROC_INST_ID_`),  
  UNIQUE KEY `ACT_UNIQ_HI_BUS_KEY` (`PROC_DEF_ID_`,`BUSINESS_KEY_`),  
  KEY `ACT_IDX_HI_PRO_INST_END` (`END_TIME_`),  
  KEY `ACT_IDX_HI_PRO_I_BUSKEY` (`BUSINESS_KEY_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_hi_taskinst 结构  
DROP TABLE IF EXISTS `act_hi_taskinst`;  
CREATE TABLE IF NOT EXISTS `act_hi_taskinst` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_DEF_KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PARENT_TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DESCRIPTION_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `OWNER_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `ASSIGNEE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `START_TIME_` DATETIME NOT NULL,  
  `CLAIM_TIME_` DATETIME DEFAULT NULL,  
  `END_TIME_` DATETIME DEFAULT NULL,  
  `DURATION_` BIGINT(20) DEFAULT NULL,  
  `DELETE_REASON_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `PRIORITY_` INT(11) DEFAULT NULL,  
  `DUE_DATE_` DATETIME DEFAULT NULL,  
  `FORM_KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_hi_varinst 结构  
DROP TABLE IF EXISTS `act_hi_varinst`;  
CREATE TABLE IF NOT EXISTS `act_hi_varinst` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `VAR_TYPE_` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `BYTEARRAY_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DOUBLE_` DOUBLE DEFAULT NULL,  
  `LONG_` BIGINT(20) DEFAULT NULL,  
  `TEXT_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `TEXT2_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME_` DATETIME(3) DEFAULT NULL,
  `LAST_UPDATED_TIME_` DATETIME(3) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_HI_PROCVAR_PROC_INST` (`PROC_INST_ID_`),  
  KEY `ACT_IDX_HI_PROCVAR_NAME_TYPE` (`NAME_`,`VAR_TYPE_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_id_group 结构  
DROP TABLE IF EXISTS `act_id_group`;  
CREATE TABLE IF NOT EXISTS `act_id_group` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_id_info 结构  
DROP TABLE IF EXISTS `act_id_info`;  
CREATE TABLE IF NOT EXISTS `act_id_info` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `USER_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `TYPE_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `VALUE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PASSWORD_` LONGBLOB,  
  `PARENT_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_id_user 结构  
DROP TABLE IF EXISTS `act_id_user`;  
CREATE TABLE IF NOT EXISTS `act_id_user` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `FIRST_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `LAST_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `EMAIL_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PWD_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PICTURE_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_id_membership 结构  
DROP TABLE IF EXISTS `act_id_membership`;  
CREATE TABLE IF NOT EXISTS `act_id_membership` (  
  `USER_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `GROUP_ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  PRIMARY KEY  (`USER_ID_`,`GROUP_ID_`),  
  KEY `ACT_FK_MEMB_GROUP` (`GROUP_ID_`),  
  CONSTRAINT `ACT_FK_MEMB_GROUP` FOREIGN KEY (`GROUP_ID_`) REFERENCES `act_id_group` (`ID_`),  
  CONSTRAINT `ACT_FK_MEMB_USER` FOREIGN KEY (`USER_ID_`) REFERENCES `act_id_user` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
  
-- 导出  表 act_re_model 结构  
DROP TABLE IF EXISTS `act_re_model`;  
CREATE TABLE IF NOT EXISTS `act_re_model` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `CATEGORY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `CREATE_TIME_` TIMESTAMP NULL DEFAULT NULL,  
  `LAST_UPDATE_TIME_` TIMESTAMP NULL DEFAULT NULL,  
  `VERSION_` INT(11) DEFAULT NULL,  
  `META_INFO_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `DEPLOYMENT_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EDITOR_SOURCE_VALUE_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EDITOR_SOURCE_EXTRA_VALUE_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_FK_MODEL_SOURCE` (`EDITOR_SOURCE_VALUE_ID_`),  
  KEY `ACT_FK_MODEL_SOURCE_EXTRA` (`EDITOR_SOURCE_EXTRA_VALUE_ID_`),  
  KEY `ACT_FK_MODEL_DEPLOYMENT` (`DEPLOYMENT_ID_`),  
  CONSTRAINT `ACT_FK_MODEL_DEPLOYMENT` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `act_re_deployment` (`ID_`),  
  CONSTRAINT `ACT_FK_MODEL_SOURCE` FOREIGN KEY (`EDITOR_SOURCE_VALUE_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),  
  CONSTRAINT `ACT_FK_MODEL_SOURCE_EXTRA` FOREIGN KEY (`EDITOR_SOURCE_EXTRA_VALUE_ID_`) REFERENCES `act_ge_bytearray` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  

-- 导出  表 act_re_procdef 结构  
DROP TABLE IF EXISTS `act_re_procdef`;  
CREATE TABLE IF NOT EXISTS `act_re_procdef` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `CATEGORY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `KEY_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `VERSION_` INT(11) NOT NULL,  
  `DEPLOYMENT_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `RESOURCE_NAME_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `DGRM_RESOURCE_NAME_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `DESCRIPTION_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `HAS_START_FORM_KEY_` TINYINT(4) DEFAULT NULL,  
  `SUSPENSION_STATE_` INT(11) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  UNIQUE KEY `ACT_UNIQ_PROCDEF` (`KEY_`,`VERSION_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_ru_execution 结构  
DROP TABLE IF EXISTS `act_ru_execution`;  
CREATE TABLE IF NOT EXISTS `act_ru_execution` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `BUSINESS_KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PARENT_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `SUPER_EXEC_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `ACT_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `IS_ACTIVE_` TINYINT(4) DEFAULT NULL,  
  `IS_CONCURRENT_` TINYINT(4) DEFAULT NULL,  
  `IS_SCOPE_` TINYINT(4) DEFAULT NULL,  
  `IS_EVENT_SCOPE_` TINYINT(4) DEFAULT NULL,  
  `SUSPENSION_STATE_` INT(11) DEFAULT NULL,  
  `CACHED_ENT_STATE_` INT(11) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  UNIQUE KEY `ACT_UNIQ_RU_BUS_KEY` (`PROC_DEF_ID_`,`BUSINESS_KEY_`),  
  KEY `ACT_IDX_EXEC_BUSKEY` (`BUSINESS_KEY_`),  
  KEY `ACT_FK_EXE_PROCINST` (`PROC_INST_ID_`),  
  KEY `ACT_FK_EXE_PARENT` (`PARENT_ID_`),  
  KEY `ACT_FK_EXE_SUPER` (`SUPER_EXEC_`),  
  CONSTRAINT `ACT_FK_EXE_PARENT` FOREIGN KEY (`PARENT_ID_`) REFERENCES `act_ru_execution` (`ID_`),  
  CONSTRAINT `ACT_FK_EXE_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),  
  CONSTRAINT `ACT_FK_EXE_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE ON UPDATE CASCADE,  
  CONSTRAINT `ACT_FK_EXE_SUPER` FOREIGN KEY (`SUPER_EXEC_`) REFERENCES `act_ru_execution` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  


-- 导出  表 act_ru_event_subscr 结构  
DROP TABLE IF EXISTS `act_ru_event_subscr`;  
CREATE TABLE IF NOT EXISTS `act_ru_event_subscr` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `EVENT_TYPE_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `EVENT_NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `ACTIVITY_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `CONFIGURATION_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `CREATED_` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_EVENT_SUBSCR_CONFIG_` (`CONFIGURATION_`),  
  KEY `ACT_FK_EVENT_EXEC` (`EXECUTION_ID_`),  
  CONSTRAINT `ACT_FK_EVENT_EXEC` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;    


-- 导出  表 act_ru_task 结构  
DROP TABLE IF EXISTS `act_ru_task`;  
CREATE TABLE IF NOT EXISTS `act_ru_task` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `PARENT_TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DESCRIPTION_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_DEF_KEY_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `OWNER_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `ASSIGNEE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `DELEGATION_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PRIORITY_` INT(11) DEFAULT NULL,  
  `CREATE_TIME_` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
  `DUE_DATE_` DATETIME DEFAULT NULL,  
  `SUSPENSION_STATE_` INT(11) DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_TASK_CREATE` (`CREATE_TIME_`),  
  KEY `ACT_FK_TASK_EXE` (`EXECUTION_ID_`),  
  KEY `ACT_FK_TASK_PROCINST` (`PROC_INST_ID_`),  
  KEY `ACT_FK_TASK_PROCDEF` (`PROC_DEF_ID_`),  
  CONSTRAINT `ACT_FK_TASK_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),  
  CONSTRAINT `ACT_FK_TASK_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),  
  CONSTRAINT `ACT_FK_TASK_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
  
-- 导出  表 act_ru_identitylink 结构  
DROP TABLE IF EXISTS `act_ru_identitylink`;  
CREATE TABLE IF NOT EXISTS `act_ru_identitylink` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL DEFAULT '',  
  `REV_` INT(11) DEFAULT NULL,  
  `GROUP_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `USER_ID_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_IDENT_LNK_USER` (`USER_ID_`),  
  KEY `ACT_IDX_IDENT_LNK_GROUP` (`GROUP_ID_`),  
  KEY `ACT_IDX_ATHRZ_PROCEDEF` (`PROC_DEF_ID_`),  
  KEY `ACT_FK_TSKASS_TASK` (`TASK_ID_`),  
  KEY `ACT_FK_IDL_PROCINST` (`PROC_INST_ID_`),  
  CONSTRAINT `ACT_FK_ATHRZ_PROCEDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),  
  CONSTRAINT `ACT_FK_IDL_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`),  
  CONSTRAINT `ACT_FK_TSKASS_TASK` FOREIGN KEY (`TASK_ID_`) REFERENCES `act_ru_task` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  
  
-- 导出  表 act_ru_job 结构  
DROP TABLE IF EXISTS `act_ru_job`;  
CREATE TABLE IF NOT EXISTS `act_ru_job` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `LOCK_EXP_TIME_` TIMESTAMP NULL DEFAULT NULL,  
  `LOCK_OWNER_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `EXCLUSIVE_` TINYINT(1) DEFAULT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROCESS_INSTANCE_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_DEF_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `RETRIES_` INT(11) DEFAULT NULL,  
  `EXCEPTION_STACK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `EXCEPTION_MSG_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `DUEDATE_` TIMESTAMP NULL DEFAULT NULL,  
  `REPEAT_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `HANDLER_TYPE_` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,  
  `HANDLER_CFG_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_FK_JOB_EXCEPTION` (`EXCEPTION_STACK_ID_`),  
  CONSTRAINT `ACT_FK_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
  


-- 导出  表 act_ru_variable 结构  
DROP TABLE IF EXISTS `act_ru_variable`;  
CREATE TABLE IF NOT EXISTS `act_ru_variable` (  
  `ID_` VARCHAR(64) COLLATE utf8_bin NOT NULL,  
  `REV_` INT(11) DEFAULT NULL,  
  `TYPE_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `NAME_` VARCHAR(255) COLLATE utf8_bin NOT NULL,  
  `EXECUTION_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `PROC_INST_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `TASK_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `BYTEARRAY_ID_` VARCHAR(64) COLLATE utf8_bin DEFAULT NULL,  
  `DOUBLE_` DOUBLE DEFAULT NULL,  
  `LONG_` BIGINT(20) DEFAULT NULL,  
  `TEXT_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  `TEXT2_` VARCHAR(4000) COLLATE utf8_bin DEFAULT NULL,  
  PRIMARY KEY  (`ID_`),  
  KEY `ACT_IDX_VARIABLE_TASK_ID` (`TASK_ID_`),  
  KEY `ACT_FK_VAR_EXE` (`EXECUTION_ID_`),  
  KEY `ACT_FK_VAR_PROCINST` (`PROC_INST_ID_`),  
  KEY `ACT_FK_VAR_BYTEARRAY` (`BYTEARRAY_ID_`),  
  CONSTRAINT `ACT_FK_VAR_BYTEARRAY` FOREIGN KEY (`BYTEARRAY_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),  
  CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),  
  CONSTRAINT `ACT_FK_VAR_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`)  
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


DROP TABLE IF EXISTS `act_evt_log`;
CREATE TABLE `act_evt_log` (
  `LOG_NR_` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TIME_STAMP_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DATA_` longblob,
  `LOCK_OWNER_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LOCK_TIME_` timestamp(3) NULL DEFAULT NULL,
  `IS_PROCESSED_` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`LOG_NR_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;